### ISSUE TITLE
Seems to import folders not in sidebars.yaml

### ISSUE THREAD

**Issue by cjoy** [acrobit/docusaurus-plugin-auto-sidebars#2]
I have a folder that I don't want to include in the sidebar, but the plugin seems to be including that as well, even if it isn't included in the sidebars.yaml file :( 

Unrelated side note - I think the docs are wrong for specifying the custom path. It says `docs` in the readme, but when I looked at the code, you're using `path`.

**Comment by ghominejad** [comment]
Hi @cjoy, I've just added the hiding option by setting `false` or an empty title for those folders you want to be hidden.

```YAML
- folder1: 
  - Parent Folder One 
  - subfolder1: Sub Folder One
  - subfolder2: Sub Folder Two
  - subfolder3: false # Hide it!
```
I hope it would be useful.
