### ISSUE TITLE
add links to sidebar

### ISSUE THREAD

**Issue by booshnelli** [acrobit/docusaurus-plugin-auto-sidebars#6]
hey, small feature request :)

would it be possible to let people define items as href links in the sidebar? this is possible with the default sidebar and would be super useful with the auto sidebar!

perhaps let people define them in the yaml? or even a seperate yaml. something where u could also define what folder they would be in, along with the label. maybe something like:
```
- folder1:
   - links:
       - ExampleSite: https://example.com
       - Google: https://google.com
   - subfolder1:
       - links:
           - Github: https://github.com
```

anyway just thought this might be a handy little feature 👍
